{ id_user,name,role,email,email_verified,status_user,remember_token,kode_statusbeli,status_beli,
    kode_statusproduksi,status_produksi, kode_satuan,nama_satuan,  status_satuan, kode_warna,nama_warna,
    status_warna,kode_ukuran,  nama_ukuran ,status_ukuran,kode_produk,
    keterangan_produk,status_produk,kode_bahanbaku,nama_bahanbaku,stok,
    keterangan_bahanbaku,status_bahanbaku,kode_belibahanbaku,total_jumlahbeli,  tgl_beli ,   
    
    kode_detail_belibahanbaku ,  jumlah_beli ,
     keterangan_detailbeli, kode_rencanaproduksi , tgl_awal  ,  
     tgl_akhir,biaya_cutting,  biaya_jahit  ,  biaya_packing  ,  jumlah_rencanaproduksi,  
      kode_detail_rencanaproduksi ,warna_bahanbaku,satuan_bahanbaku,
      jumlah_perlu_stokbahanbaku, kode_restock , no_faktur ,  total_hargaitem , tgl_restock,
       kode_detail_restock  ,harga_item , 
       jumlah_item,keterangan_restock, kode_produksipakaian_cutting  ,nama_produk,
       warna_produk,ukuran_produk,total_jumlahberhasil_cutting,total_jumlahgagal_cutting,
       total_produksi_pakaian_cutting,tanggal_awal,tanggal_selesai_cutting,
       kode_detail_produksipakaian_cutting,
       tanggal_kerja_cutting,jumlah_berhasil_cutting,
       jumlah_gagal_cutting,total_berhasildangagal_cutting,upah_kerja_cutting,kode_produksipakaian_jahit,
       ,
       total_jumlahberhasil_jahit,total_jumlahgagal_jahit,total_produksi_pakaian_jahit,
       ,tanggal_selesai_jahit,kode_detail_produksipakaian_jahit,
       ,tanggal_kerja_jahit1
       ,jumlah_berhasil_jahit,jumlah_gagal_jahit,total_berhasildangagal_jahit,
       upah_kerja_jahit,kode_produksipakaian_packing,
       ,total_jumlahberhasil_packing,total_jumlahgagal_packing,total_produksi_pakaian_packing,
       tanggal_selesai_packing,kode_detail_produksipakaian_packing,
       tanggal_kerja_packing,
       jumlah_berhasil_packing,jumlah_gagal_packing,
       total_berhasildangagal_packing,upah_kerja_packing}